apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: broker-to-s3
  annotations:
    meta.helm.sh/release-name: quarkus-pipeline
    meta.helm.sh/release-namespace: camel-dev
  labels:
    system: default-application
spec:
  params:
    - default: 'https://github.com/GuilhermeCamposo/camel_development_starter'
      description: component source Git pepository
      name: git-url
      type: string
    - default: main
      description: component source Git revision
      name: git-revision
      type: string
    - default: camel-examples/broker-to-s3/src/main/docker/Dockerfile.jvm
      description: path to Dockerfile
      name: dockerfilePath
      type: string
    - default: 'image-registry.openshift-image-registry.svc:5000/camel-dev/broker-to-s3'
      description: container image
      name: image
      type: string
    - default: latest
      description: image tag
      name: version
      type: string
    - default: camel-examples/broker-to-s3
      description: path to the directory where to package and build image
      name: context-dir  
  tasks:
    - name: clone
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source-output
    - name: build
      params:
        - name: GOALS
          value:
            - compile
        - name: CONTEXT_DIR
          value: '$(params.context-dir)'            
      runAfter:
        - clone
      taskRef:
        kind: Task
        name: maven
      workspaces:
        - name: source
          workspace: source-output
        - name: maven-settings
          workspace: maven-settings
        - name: maven-local-repo
          workspace: maven-local-repo          
    - name: package
      params:
        - name: GOALS
          value:
            - package
            - '-DskipTests'
        - name: CONTEXT_DIR
          value: '$(params.context-dir)'      
      runAfter:
        - build
      taskRef:
        kind: Task
        name: maven
      workspaces:
        - name: source
          workspace: source-output
        - name: maven-settings
          workspace: maven-settings
        - name: maven-local-repo
          workspace: maven-local-repo 
    - name: build-container-image
      params:
        - name: IMAGE
          value: '$(params.image):$(params.version)'
        - name: DOCKERFILE
          value: $(params.dockerfilePath)
        - name: CONTEXT
          value: $(params.context-dir)          
      runAfter:
        - package
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: source-output
  workspaces:
    - name: source-output
    - name: maven-settings
    - name: maven-local-repo
